### ISSUE TITLE
Attribute matchers

### ISSUE THREAD

**Issue by hurrymaplelad** [goodeggs/chai-webdriver#10]
I want to assert the href of an `<a/>` matches a regex.

I like the looks of the [chai-jquery api](https://github.com/chaijs/chai-jquery).  How's a PR to add similar assertions sound?

``` js
expect('body').dom.to.have.attr('foo', 'bar')
expect('body').dom.to.have.attr('foo').match(/bar/)
```

**Comment by serhalp** [comment]
Closed by https://github.com/goodeggs/chai-webdriver/pull/15 and https://github.com/goodeggs/chai-webdriver/pull/16.
