### ISSUE TITLE
Make compatible with Chai v2.0

### ISSUE THREAD

**Issue by akbiggs** [goodeggs/chai-webdriver#25]
Chai has recently upgraded to version 2.0. This means that if a user installs chai without specifying a version and then attempts to install chai-webdriver, they will receive an error saying that the package chai does not satisfy its siblings' peerDependencies requirements.

**Comment by demands** [comment]
Odd, we don't actually list chai as a `peerDependency`. Any chance you could paste a copy of the error message? Thanks.

**Comment by akbiggs** [comment]
After 1.1.0, it seems like [chai-webdriver-promised](https://github.com/b3nj4m/chai-webdriver) has outdated dependencies now, causing a dependency conflict.

```
$ npm install chai chai-webdriver --save

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "chai" "chai-webdriver" "--save"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package chai does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer chai-as-promised@4.2.0 wants chai@>= 1.7.0 < 3
npm ERR! peerinvalid Peer chai-webdriver@1.1.0 wants chai@>= 1 <= 2
npm ERR! peerinvalid Peer chai-webdriver-promised@4.0.3 wants chai@1.x
```

**Comment by schlaup** [comment]
Now NPM install of the plugin does not work with Chai 2.1:

    npm ERR! peerinvalid The package chai does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer chai-as-promised@4.2.0 wants chai@>= 1.7.0 < 3
    npm ERR! peerinvalid Peer sinon-chai@2.7.0 wants chai@>=1.9.2 <3
    npm ERR! peerinvalid Peer chai-webdriver@1.1.0 wants chai@>= 1 <= 2

I guess you should use

    "chai": ">= 1 < 3"

instead of

    "chai": ">= 1 <= 2"

**Comment by demands** [comment]
Right you are. I've just published `v.1.1.1` which will hopefully deal with this problem once and for all. Thanks for the reports!

**Comment by aleris** [comment]
Chai is now at "version": "3.4.2", failing again:

npm ERR! peerinvalid The package chai@3.4.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer chai-webdriver@1.1.1 wants chai@>= 1 < 3

**Comment by serhalp** [comment]
@aleris This is fixed in `v1.2.0`.

**Comment by VJag** [comment]
Getting this issue while trying to install chai-webdriver-promised

D:\UI>npm install chai-webdriver-promised
frontend@1.0.0 D:\UI
+-- UNMET PEER DEPENDENCY chai@3.5.0
+-- chai-webdriver-promised@4.0.3  extraneous
+-- jasmine-core@2.4.1
+-- require@2.4.20  extraneous
`-- requirejs@2.2.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN chai-webdriver-promised@4.0.3 requires a peer of chai@1.x but none was installed.

**Comment by serhalp** [comment]
Hi @VJag, it sounds like you're looking for a different repo named [`chai-webdriver-promised`](https://www.npmjs.com/package/chai-webdriver-promised), which appears to be a fork of this repo (`chai-webdriver`).  I'd try posting an issue over there.

(Although, my two cents: that's not really an issue – you just need to manually install `chai@1.x` (`npm install chai@1.x`), because `chai-webdriver-promised` specifies it as a peer dependency and, as of `npm@3`, those aren't installed automatically.)
