### ISSUE TITLE
Not working with chai 3.x

### ISSUE THREAD

**Issue by jenius** [goodeggs/chai-webdriver#28]
Noticed that the peer dep was off from the latest version, forked and bumped the peer dep version, and ran the tests to make sure it still worked ok. Tests are stalling out indefinitely and not running :cry:

**Comment by whittle** [comment]
+1

**Comment by neodon** [comment]
+1 Would you accept a patch to resolve this?

**Comment by anthonybruno** [comment]
+ 1

**Comment by jurgob** [comment]
+1

**Comment by serhalp** [comment]
Fixed in `v1.2.0`.
