### ISSUE TITLE
README cofused me 

### ISSUE THREAD

**Issue by priyanshus** [goodeggs/chai-webdriver#29]
Readme of this repo confused me by showing different ways of using `.not`. E.g.

```
expect('.toggle-pane').dom.to.not.be.visible(); //to.not
hai.expect('#site-container h1.heading').dom.to.not.contain.text("I'm a kitty!"); //to.not
expect(selector).dom.not.to.have.style('property', 'value'); //not.to
```

Could you please maintain the integrity of Readme by using `.not` only in one way and is it possible to use `.not` in both the ways?

**Comment by serhalp** [comment]
See [chai documentation](http://chaijs.com/api/bdd/) about chaining. This isn't specific to chai-webdriver.
