### ISSUE TITLE
Unhandled error using mocha

### ISSUE THREAD

**Issue by BuonOmo** [goodeggs/chai-webdriver#32]
I’m having a hard time with chai webdriver,

http://stackoverflow.com/q/40167054/6320039

I’m starting to guess it may be an error coming from the plugin, that’s why I’m putting it here

**Comment by serhalp** [comment]
Sorry we haven't responded for so long! I'm going to close this, but please feel free to respond if you still need help.

**Comment by BuonOmo** [comment]
I don’t remember the issue anymore...
